language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install coverage
  - pip install coveralls
  - pip install flake8

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - black .

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite_swe1_app,polls manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted AKIA3NOQGZRQYWHHDUJC="
  secret_access_key:
    secure: "Encypted LLRzxAAKIkUpD0HNxMNyDxWahTkKm/QsC5pHDtZN="
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-784805055585"
  on:
    repo: ZenoWang1999/swe1-app
    branch: main