language: python
python:
- 3.9
install:
- pip install -r requirements.txt
- pip install black
- pip install coverage
- pip install coveralls
- pip install flake8
before_script:
- python manage.py migrate
- python manage.py collectstatic --noinput
- black .
script:
- black --check .
- flake8 .
- coverage run --source=polls manage.py test
after_script:
- coveralls
after_success:
  coveralls
deploy:
- provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $SECRET_KEY
  region: $REGION
  app: $APP
  env: $ENV
  bucket_name: $BUCKET
  on:
    branch: main